# ---------------------------------------------------------------------------
# See the NOTICE file distributed with this work for additional
# information regarding copyright ownership.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA, or see the FSF site: http://www.fsf.org.
# ---------------------------------------------------------------------------

###############################################################################
# This contains the translations of the module in the default language
# (generally English).
#
# Translation key syntax:
#   <short top level project name>.<short module name>.<propertyName>
#   where:
#   * <short top level project name> = top level project name without the "xwiki-" prefix,
#                                     for example: commons, rendering, platform, enterprise, manager, etc
#   * <short module name> = the name of the Maven module without the <short top level project name> prefix,
#                           for example: oldcore, scheduler, activitystream, etc
#   * <propertyName> = the name of the property using camel case,
#                      for example updateJobClassCommitComment
#
# Comments: it's possible to add some detail about a key to make easier to
#   translate it by adding a comment before it. To make sure a comment is not
#   assigned to the following key use at least three sharps (###) for the comment
#   or after it.
#
# Deprecated keys:
#   * when deleting a key it should be moved to deprecated section at the end
#     of the file (between #@deprecatedstart and #@deprecatedend) and associated to the
#     first version in which it started to be deprecated
#   * when renaming a key, it should be moved to the same deprecated section
#     and a comment should be added with the following syntax:
#     #@deprecated new.key.name
#     old.key.name=Some translation
###############################################################################

oidc.template.consent.title=OpenID Connect Consent
oidc.template.consent.question=The client {0} is requesting access to the following:
oidc.template.consent.answer.accept=Accept
oidc.template.consent.answer.refuse=Refuse
oidc.template.consent.clais.scope=Scope
oidc.template.consent.clais.idtoken=ID Token
oidc.template.consent.clais.userinfo=User informations

XWiki.OIDC.Provider.ClientClass_id=Client ID
XWiki.OIDC.Provider.ClientClass_secret=Client Secret
XWiki.OIDC.Provider.ClientClass_redirectURIs=Allowed redirect URIs
XWiki.OIDC.Provider.ClientClass_redirectURIs_hint=The list of URIs to which the provider is allowed to redirect. You can specify multiple URIs by separating them with commas or white spaces. For example: https://myapp.com/callback, https://myapp.com/redirect.
XWiki.OIDC.Provider.ClientClass_logoutURI=Back-channel logout URI
XWiki.OIDC.Provider.ClientClass_logoutURI_hint=The URI that the provider will call to notify the client of a logout event, if the client supports back-channel logout.

oidc.provider.clients.description=This document contains the metadata about the applications that will be able to use the OpenID Connect provider for authentication. You can modify them using the object editor. The clients also have a list of allowed redirect URIs, which are the URIs that the provider will redirect to after authentication. It's also possible to set a client with empty metadata to allow any application to act as OpenID Connect relying party.

oidc.provider.admin.title=Provider
oidc.provider.admin.clients.title=Clients
oidc.provider.admin.clients.description=The provider has two different modes: the "dynamic" mode and the "static" mode. It's generally recommended to use the "static" mode in production environments, as I give more control on who can be trusted as relying party.
oidc.provider.admin.clients.mode.dynamic=Dynamic mode
oidc.provider.admin.clients.mode.dynamic.hint=In this mode, any client can be used for OpenID Connect authentication, without registration.
oidc.provider.admin.clients.mode.dynamic.save=Switch to dynamic mode
oidc.provider.admin.clients.mode.dynamic.saved=Switched to dynamic mode
oidc.provider.admin.clients.mode.static=Static mode
oidc.provider.admin.clients.mode.static.hint=In this mode, only clients registered by an administrator can be used for OpenID Connect authentication.
oidc.provider.admin.clients.mode.static.save=Switch to static mode
oidc.provider.admin.clients.mode.static.saved=Switched to static mode
oidc.provider.admin.editClients=Edit clients
oidc.provider.admin.clients.mode.save=Save
